name: My Github workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  myworkflowjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my workflow job"
      - run: echo "This job runs on push and pull request to main branch"
      - run: echo "checkout the repository"
        uses: actions/checkout@v2
      